title: VictoriaMetrics docs
lang: en
#description:

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile

plugins:
  - github-pages