title: VictoriaMetrics docs
lang: en
email: info@victoriametrics.com
description: >
  The Aspiring Monitoring Solution

#google_analytics: UA-129683199-1

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile

plugins:
  - github-pages